# Generated by Django 3.0.8 on 2022-11-10 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contrasena',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='correoUsu',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.CreateModel(
            name='documento',
            fields=[
                ('idDoc', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.FileField(blank=True, null=True, upload_to='archivo/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
