# Generated by Django 3.0.8 on 2022-11-22 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20221110_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'verbose_name': 'documento', 'verbose_name_plural': 'documentos'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='documento',
            name='usuario',
        ),
        migrations.CreateModel(
            name='enviar',
            fields=[
                ('idEnvio', models.AutoField(max_length=30, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('mensaje', models.TextField(max_length=1000)),
                ('etiqueta', models.CharField(max_length=50)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs1', to=settings.AUTH_USER_MODEL)),
                ('emisario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs2', to=settings.AUTH_USER_MODEL)),
                ('idDoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs1', to='app.documento')),
            ],
            options={
                'verbose_name': 'enviar',
                'verbose_name_plural': 'enviados',
            },
        ),
    ]
