# Generated by Django 3.0.8 on 2022-11-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20221121_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviar',
            name='idEnvio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
