# Generated by Django 3.0.8 on 2022-11-24 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20221121_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='coleccion',
            fields=[
                ('idColec', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('idEnvio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enviar', to='app.enviar')),
            ],
        ),
    ]
