# Generated by Django 3.0.8 on 2022-11-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20221124_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[(5, 'asesor de trabajo de grado'), (1, 'coordinador de trabajo de grado'), (3, 'jurado'), (6, 'profesor'), (4, 'director de trabajo de grado'), (2, 'coordinador de práctica')], default=1),
        ),
    ]
