# Generated by Django 3.0.8 on 2022-11-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('coordinador de trabajo de grado', 'coordinador de trabajo de grado'), ('director de trabajo de grado', 'director de trabajo de grado'), ('profesor', 'profesor'), ('asesor de trabajo de grado', 'asesor de trabajo de grado'), ('jurado', 'jurado'), ('coordinador de práctica', 'coordinador de práctica')], default=1, max_length=100),
        ),
    ]
