# Generated by Django 3.0.8 on 2022-11-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20221125_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviar',
            name='etiqueta',
            field=models.CharField(choices=[('Aprobada', 'Aprobada'), ('Pendiente', 'Pendiente'), ('Denegada', 'Aprobada')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Director de trabajo de grado', 'Director de trabajo de grado'), ('Jurado', 'Jurado'), ('Coordinador de práctica', 'Coordinador de práctica'), ('Profesor', 'Profesor'), ('Asesor de trabajo de grado', 'Asesor de trabajo de grado'), ('Coordinador de trabajo de grado', 'Coordinador de trabajo de grado')], default=1, max_length=100),
        ),
    ]
